/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemontrainercard;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Apagar extends javax.swing.JFrame {

    /**
     * Creates new form Apagar
     */
    public Apagar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickableLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        BtnExcluir = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        clickableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clickableLabel.setForeground(new java.awt.Color(255, 255, 255));
        clickableLabel.setText("Voltar");
        clickableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickableLabelMouseClicked(evt);
            }
        });
        getContentPane().add(clickableLabel);
        clickableLabel.setBounds(10, 10, 80, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 350, 70, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 349, 70, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(330, 350, 180, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(600, 350, 200, 30);

        BtnExcluir.setBackground(new java.awt.Color(0, 153, 153));
        BtnExcluir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/heavyball.png"))); // NOI18N
        BtnExcluir.setText("Apagar meu card");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcluir);
        BtnExcluir.setBounds(370, 430, 300, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/trBig.gif"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1030, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableLabelMouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_clickableLabelMouseClicked

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        String trainername = txtNome.getText();
    String password = new String(txtSenha.getPassword());

    try {
Connection conn = DriverManager.getConnection("jdbc:sqlite:trainercards.db");
        Statement stmt = conn.createStatement();

        // Check if the username already exists
        String checkQuery = "SELECT * FROM trainers WHERE trainerName = '" + trainername +  "' AND trainerPass = '" + password + "'";
        ResultSet checkResult = stmt.executeQuery(checkQuery);
        if (checkResult.next()) {}
        else{
            JOptionPane.showMessageDialog(this, "Nome de treinador ou senha Invalidos!");
            stmt.close();
            conn.close();
            return;
        }
        String insertQuery = " DELETE FROM trainers WHERE trainerName = '"+trainername+ "' AND trainerPass = '" + password + "'";
        int rowsAffected = stmt.executeUpdate(insertQuery);

        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Sua conta foi apagada!");
            
            // Perform further actions or open a new window
        } else {
            JOptionPane.showMessageDialog(this, "A tentativa falhou!");
        }

        stmt.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro conectando com o banco de dados: " + e.getMessage());
    }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JLabel background;
    private javax.swing.JLabel clickableLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
