/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemontrainercard;

import javax.swing.*;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class CardView extends javax.swing.JFrame {


    
    /**
     * Creates new form CardView
     */
    public CardView() {
        initComponents();
        String Trainername = DatabaseConnection.getLoginId();
        lblTrainerName.setText(Trainername);
        int[] TeamMember = new int[6];
        String[] SpritePath =  new String[6];
        try{
Connection conn = DriverManager.getConnection("jdbc:sqlite:trainercards.db");
            Statement stmt = conn.createStatement();
            
            String checkname = "SELECT * FROM trainers WHERE trainerName = '"+Trainername+"' ";
            ResultSet dadosTreinador = stmt.executeQuery(checkname);
            while(dadosTreinador.next()) {
                for(int i=0;i<=5;i++){
            TeamMember[i] = dadosTreinador.getInt("pokemon"+(i+1));
            SpritePath[i] = String.valueOf(TeamMember[i]+".gif");
                    System.out.println(SpritePath[i]);
                    
                   
                    
                }
            int id = dadosTreinador.getInt("tid");   
            lblTrainerId.setText(String.valueOf(id));
                
            poke1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[0]+"")));
            poke2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[1]+"")));
            poke3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[2]+"")));
            poke4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[3]+"")));
            poke5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[4]+"")));
            poke6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeSprites/"+SpritePath[5]+"")));
                
            int cor = dadosTreinador.getInt("cardColor");   
            String corcard = String.valueOf("cardBackground"+cor+".png");
            fundoCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardBackgrounds/"+corcard+"")));
            if(cor == 3 || cor == 4 || cor == 2 || cor == 1){
                lblTrainerId.setForeground(new java.awt.Color(255, 255, 255));
            }
            
            
            int spriteNumber = dadosTreinador.getInt("trainerClass");   
            String tSprite = String.valueOf("trainer"+spriteNumber+".png");
            trainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trainers/"+tSprite+"")));
                
                
            
                
                                           }
            

            
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Ocorreu um erro na comunicação com o banco de dados. ERROR: "+e);
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrainerId = new javax.swing.JLabel();
        lblTrainerName = new javax.swing.JLabel();
        trainer = new javax.swing.JLabel();
        poke1 = new javax.swing.JLabel();
        poke2 = new javax.swing.JLabel();
        poke3 = new javax.swing.JLabel();
        poke4 = new javax.swing.JLabel();
        poke5 = new javax.swing.JLabel();
        poke6 = new javax.swing.JLabel();
        clickableLabel = new javax.swing.JLabel();
        fundoCard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        lblTrainerId.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lblTrainerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrainerId.setToolTipText("");
        getContentPane().add(lblTrainerId);
        lblTrainerId.setBounds(500, 40, 470, 60);

        lblTrainerName.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        getContentPane().add(lblTrainerName);
        lblTrainerName.setBounds(60, 135, 550, 55);
        getContentPane().add(trainer);
        trainer.setBounds(700, 100, 320, 520);
        getContentPane().add(poke1);
        poke1.setBounds(51, 230, 190, 100);
        getContentPane().add(poke2);
        poke2.setBounds(263, 230, 190, 100);
        getContentPane().add(poke3);
        poke3.setBounds(481, 230, 190, 100);
        getContentPane().add(poke4);
        poke4.setBounds(51, 350, 190, 100);
        getContentPane().add(poke5);
        poke5.setBounds(263, 350, 190, 100);
        getContentPane().add(poke6);
        poke6.setBounds(481, 350, 190, 100);

        clickableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clickableLabel.setForeground(new java.awt.Color(255, 255, 255));
        clickableLabel.setText("Voltar");
        clickableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickableLabelMouseClicked(evt);
            }
        });
        getContentPane().add(clickableLabel);
        clickableLabel.setBounds(20, 0, 80, 30);

        fundoCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardBackgrounds/cardBackground4.png"))); // NOI18N
        getContentPane().add(fundoCard);
        fundoCard.setBounds(0, 0, 1020, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void clickableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableLabelMouseClicked
        // TODO add your handling code here:
        
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_clickableLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickableLabel;
    private javax.swing.JLabel fundoCard;
    private javax.swing.JLabel lblTrainerId;
    private javax.swing.JLabel lblTrainerName;
    private javax.swing.JLabel poke1;
    private javax.swing.JLabel poke2;
    private javax.swing.JLabel poke3;
    private javax.swing.JLabel poke4;
    private javax.swing.JLabel poke5;
    private javax.swing.JLabel poke6;
    private javax.swing.JLabel trainer;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NomedoTreinador
     */
    
    }

    /**
     * @param NomedoTreinador the NomedoTreinador to set
     */
    

