/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemontrainercard;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Login extends javax.swing.JFrame {

 
 /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        clickableLabel = new javax.swing.JLabel();
        idTreinador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Forneça o Nome do Treinador:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 150, 480, 60);

        btnVer.setBackground(new java.awt.Color(255, 255, 255));
        btnVer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/pokeball.png"))); // NOI18N
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(200, 290, 300, 150);

        clickableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clickableLabel.setText("Voltar");
        clickableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickableLabelMouseClicked(evt);
            }
        });
        getContentPane().add(clickableLabel);
        clickableLabel.setBounds(0, 0, 80, 30);

        idTreinador.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        idTreinador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTreinadorActionPerformed(evt);
            }
        });
        getContentPane().add(idTreinador);
        idTreinador.setBounds(130, 210, 470, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokeball-pokemon-minimal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableLabelMouseClicked
        // TODO add your handling code here:
     new Menu().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_clickableLabelMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // Codigo do botão Visualizar:
        String userid = idTreinador.getText();
          String nomeTreinador = idTreinador.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TrainerCards", "root", "Victor456");
            Statement stmt = conn.createStatement();
            
            String select = "SELECT * FROM trainers WHERE trainername = '"+ nomeTreinador +"'";
            ResultSet checaNome = stmt.executeQuery(select);
        if(checaNome.next()){
                loginInBetween.setLoginId(nomeTreinador);
            new CardView().setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Nome de treinador não encontrado!");
        }   
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro conectando com o banco de dados: " + e.getMessage());
        }
        
        
         
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_btnVerActionPerformed

    private void idTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel clickableLabel;
    public javax.swing.JTextField idTreinador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NomedoTreinador
     */
    

    /**
     * @param NomedoTreinador the NomedoTreinador to set
     */
    

    /**
     * @return the CardView
     */
    

    /**
     * @param CardView the CardView to set
     */
    
}
