/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemontrainercard;



/**
 *
 * @author 920415
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
   
    public Menu() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        clickableLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        btnCriar.setBackground(new java.awt.Color(0, 153, 153));
        btnCriar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/pokeball.png"))); // NOI18N
        btnCriar.setText("Criar meu card");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar);
        btnCriar.setBounds(110, 360, 300, 60);

        btnVer.setBackground(new java.awt.Color(0, 153, 153));
        btnVer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/ultraball.png"))); // NOI18N
        btnVer.setText("Ver meu card");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(630, 360, 300, 60);

        btnEditar.setBackground(new java.awt.Color(0, 153, 153));
        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/greatball.png"))); // NOI18N
        btnEditar.setText("Editar meu card");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(110, 480, 300, 60);

        BtnExcluir.setBackground(new java.awt.Color(0, 153, 153));
        BtnExcluir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/masterball.png"))); // NOI18N
        BtnExcluir.setText("Apagar meu card");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcluir);
        BtnExcluir.setBounds(630, 480, 300, 60);

        clickableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clickableLabel.setText("Sair");
        clickableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickableLabelMouseClicked(evt);
            }
        });
        getContentPane().add(clickableLabel);
        clickableLabel.setBounds(10, 10, 34, 21);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokeballIcon/premierball.png"))); // NOI18N
        jLabel2.setText("Trainer Card Maker");
        jLabel2.setPreferredSize(new java.awt.Dimension(335, 50));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 120, 730, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Hoen background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // Codigo do botão criar:
        new Cadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // Codigo do botão Visualizar:
        new Login().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void clickableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableLabelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_clickableLabelMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Codigo do botão editar:
        new Atualizar().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // Codigo do botão Apagar:
        new Apagar().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel clickableLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
